apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uat-otter-manager
  name: uat-otter-manager
  namespace: uat-otter
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: uat-otter-manager
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uat-otter-manager
    spec:
      containers:
        - image: >-
            toplist-registry-vpc.cn-shanghai.cr.aliyuncs.com/88/tl-otter:uat-otter-manager-4.2.18
          imagePullPolicy: Always
          name: uat-otter-manager
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/local/manager.deployer-4.2.18/conf/otter.properties
              name: volume-uat-otter-config
              subPath: otter-manager.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: uat-otter-config
          name: volume-uat-otter-config
